<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Academic History – {{ $student->name }}</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #222; }
    .header { text-align: center; border-bottom: 2px solid #1e3a5f; padding-bottom: 10px; margin-bottom: 14px; }
    .header h2 { margin: 0; color: #1e3a5f; font-size: 15px; }
    .year-heading { background: #1e3a5f; color: #fff; padding: 5px 8px; margin: 12px 0 4px; font-size: 11px; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
    th { background: #e0e7ff; padding: 4px 8px; text-align: left; font-size: 9px; }
    td { padding: 3px 8px; border-bottom: 1px solid #f0f4f8; }
    .school-list { margin: 0 0 12px; padding: 0; list-style: none; }
    .school-list li { padding: 2px 0; }
    .grade-A { color: #059669; } .grade-W { color: #dc2626; }
    .footer { margin-top: 30px; font-size: 9px; color: #888; text-align: center; }
</style>
</head>
<body>
<div class="header">
    <h2>Y GRO Student Management System</h2>
    <p style="margin:4px 0 0;color:#555;font-size:12px;">Full Academic History – {{ $student->name }}</p>
</div>

<table style="margin-bottom:14px;">
    <tr><th>Contact</th><td>{{ $student->contact ?? '–' }}</td><th>Stream</th><td>{{ $student->stream?->name ?? 'N/A' }}</td></tr>
    <tr><th>O/L Index</th><td>{{ $student->ol_index ?? '–' }}</td><th>A/L Index</th><td>{{ $student->al_index ?? '–' }}</td></tr>
</table>

<strong>School History:</strong>
<ul class="school-list">
@foreach($student->schoolHistories as $h)
    <li>– {{ $h->school->name }} ({{ $h->from_year }} – {{ $h->to_year ?? 'Present' }})</li>
@endforeach
</ul>

@forelse($marks as $year => $yearMarks)
<div class="year-heading">{{ $year }}</div>
@foreach($yearMarks->groupBy('term') as $term => $termMarks)
<strong style="font-size:10px;">Term {{ $term }}</strong>
<table>
    <thead><tr><th>Subject</th><th>Marks</th><th>Grade</th></tr></thead>
    <tbody>
    @foreach($termMarks as $m)
        <tr>
            <td>{{ $m->subject->name }}</td>
            <td>{{ $m->marks }}</td>
            <td class="grade-{{ $m->grade_letter }}">{{ $m->grade_letter }}</td>
        </tr>
    @endforeach
    </tbody>
</table>
@endforeach
@empty
<p style="text-align:center;color:#888;">No academic records found.</p>
@endforelse

<div class="footer">Generated by Y GRO Student Management System · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
