<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Distribution Report – {{ $student->name }}</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color:#222; }
    .header { text-align:center; border-bottom:2px solid #1e3a5f; padding-bottom:10px; margin-bottom:14px; }
    .header h2 { margin:0; color:#1e3a5f; font-size:15px; }
    table { width:100%; border-collapse:collapse; }
    th { background:#1e3a5f; color:#fff; padding:5px 8px; text-align:left; font-size:10px; }
    td { padding:4px 8px; border-bottom:1px solid #eee; }
    .total-row { background:#f0f4f8; font-weight:bold; }
    .footer { margin-top:30px; font-size:9px; color:#888; text-align:center; }
</style>
</head>
<body>
<div class="header">
    <h2>Y GRO Student Management System</h2>
    <p style="margin:4px 0 0;color:#555;font-size:12px;">Welfare Distribution Report – {{ $student->name }}</p>
</div>

<table>
    <thead><tr><th>#</th><th>Product</th><th>Year</th><th>Qty</th><th>Unit Price</th><th>Total</th><th>Date Given</th></tr></thead>
    <tbody>
    @foreach($distributions as $i => $d)
        <tr>
            <td>{{ $i+1 }}</td>
            <td>{{ $d->product->name }}</td>
            <td>{{ $d->academicYear->year }}</td>
            <td>{{ $d->quantity }}</td>
            <td>Rs. {{ number_format($d->unit_price,2) }}</td>
            <td>Rs. {{ number_format($d->quantity * $d->unit_price,2) }}</td>
            <td>{{ $d->date_given->format('d M Y') }}</td>
        </tr>
    @endforeach
    <tr class="total-row">
        <td colspan="5">Total Support Since Admission</td>
        <td colspan="2">Rs. {{ number_format($total,2) }}</td>
    </tr>
    </tbody>
</table>

<div class="footer">Generated by Y GRO Student Management System · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
