<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Year-wise Expense Report</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color:#222; }
    .header { text-align:center; border-bottom:2px solid #1e3a5f; padding-bottom:10px; margin-bottom:14px; }
    .header h2 { margin:0; color:#1e3a5f; font-size:15px; }
    table { width:100%; border-collapse:collapse; }
    th { background:#1e3a5f; color:#fff; padding:5px 8px; text-align:left; font-size:10px; }
    td { padding:4px 8px; border-bottom:1px solid #eee; }
    .total-row { background:#f0f4f8; font-weight:bold; }
    .footer { margin-top:30px; font-size:9px; color:#888; text-align:center; }
</style>
</head>
<body>
<div class="header">
    <h2>Y GRO Student Management System</h2>
    <p style="margin:4px 0 0;color:#555;">Year-wise Welfare Expense Report (2010–{{ date('Y') }})</p>
</div>
<table>
    <thead><tr><th>Academic Year</th><th>Total Items Given</th><th>Total Expense (Rs.)</th></tr></thead>
    <tbody>
    @php $grandTotal = 0; $grandQty = 0; @endphp
    @foreach($years as $row)
        @php $grandTotal += $row->total_expense; $grandQty += $row->total_quantity; @endphp
        <tr>
            <td>{{ $row->academicYear->year }}</td>
            <td>{{ $row->total_quantity }}</td>
            <td>Rs. {{ number_format($row->total_expense,2) }}</td>
        </tr>
    @endforeach
    <tr class="total-row">
        <td>Grand Total</td>
        <td>{{ $grandQty }}</td>
        <td>Rs. {{ number_format($grandTotal,2) }}</td>
    </tr>
    </tbody>
</table>
<div class="footer">Generated by Y GRO Student Management System · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
