<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Product Summary Report</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color:#222; }
    .header { text-align:center; border-bottom:2px solid #1e3a5f; padding-bottom:10px; margin-bottom:14px; }
    .header h2 { margin:0; color:#1e3a5f; font-size:15px; }
    table { width:100%; border-collapse:collapse; }
    th { background:#1e3a5f; color:#fff; padding:5px 8px; text-align:left; font-size:10px; }
    td { padding:4px 8px; border-bottom:1px solid #eee; }
    .total-row { background:#f0f4f8; font-weight:bold; }
    .footer { margin-top:30px; font-size:9px; color:#888; text-align:center; }
</style>
</head>
<body>
<div class="header">
    <h2>Y GRO Student Management System</h2>
    <p style="margin:4px 0 0;color:#555;">Product-wise Welfare Summary Report</p>
</div>
<table>
    <thead><tr><th>Product</th><th>Current Price</th><th>Total Qty Distributed</th><th>Total Value (Rs.)</th></tr></thead>
    <tbody>
    @php $grand = 0; @endphp
    @foreach($products as $p)
        @php $grand += $p->total_value ?? 0; @endphp
        <tr>
            <td>{{ $p->name }}</td>
            <td>Rs. {{ number_format($p->price,2) }}</td>
            <td>{{ $p->total_quantity ?? 0 }}</td>
            <td>Rs. {{ number_format($p->total_value ?? 0,2) }}</td>
        </tr>
    @endforeach
    <tr class="total-row">
        <td colspan="3">Total</td>
        <td>Rs. {{ number_format($grand,2) }}</td>
    </tr>
    </tbody>
</table>
<div class="footer">Generated by Y GRO Student Management System · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
