<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Term {{ $request->term }} Report – {{ $student->name }}</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
    .header { text-align: center; border-bottom: 2px solid #1e3a5f; padding-bottom: 12px; margin-bottom: 16px; }
    .header h2 { margin: 0; color: #1e3a5f; font-size: 16px; }
    .header h3 { margin: 4px 0 0; font-size: 13px; color: #555; }
    .info-grid { width: 100%; margin-bottom: 16px; }
    .info-grid td { padding: 3px 8px; }
    .info-grid .label { font-weight: bold; color: #555; width: 140px; }
    table.marks { width: 100%; border-collapse: collapse; margin-top: 10px; }
    table.marks th { background: #1e3a5f; color: #fff; padding: 6px 10px; text-align: left; font-size: 10px; }
    table.marks td { padding: 5px 10px; border-bottom: 1px solid #eee; }
    .grade-A { color: #059669; font-weight: bold; }
    .grade-W { color: #dc2626; font-weight: bold; }
    .total-row { background: #f0f4f8; font-weight: bold; }
    .footer { margin-top: 30px; font-size: 9px; color: #888; text-align: center; }
</style>
</head>
<body>
<div class="header">
    <h2>Y GRO Student Management System</h2>
    <h3>Term {{ $request->term }} Progress Report – Academic Year {{ $academicYear->year }}</h3>
</div>

<table class="info-grid">
    <tr><td class="label">Student Name:</td><td>{{ $student->name }}</td><td class="label">Grade:</td><td>Grade {{ $marks->first()?->grade ?? '–' }}</td></tr>
    <tr><td class="label">Stream:</td><td>{{ $student->stream?->name ?? 'N/A' }}</td><td class="label">Term:</td><td>Term {{ $request->term }}</td></tr>
    <tr><td class="label">O/L Index:</td><td>{{ $student->ol_index ?? '–' }}</td><td class="label">A/L Index:</td><td>{{ $student->al_index ?? '–' }}</td></tr>
</table>

<table class="marks">
    <thead><tr><th>#</th><th>Subject</th><th>Marks</th><th>Grade</th><th>Remarks</th></tr></thead>
    <tbody>
    @php $total = 0; $count = 0; @endphp
    @forelse($marks as $i => $m)
        @php $total += $m->marks; $count++; @endphp
        <tr>
            <td>{{ $i+1 }}</td>
            <td>{{ $m->subject->name }}</td>
            <td>{{ $m->marks }}</td>
            <td class="grade-{{ $m->grade_letter }}">{{ $m->grade_letter }}</td>
            <td>{{ $m->remarks ?? '' }}</td>
        </tr>
    @empty
        <tr><td colspan="5" style="text-align:center;color:#888;padding:12px;">No marks recorded for this term.</td></tr>
    @endforelse
    @if($count > 0)
    <tr class="total-row">
        <td colspan="2">Total / Average</td>
        <td>{{ $total }} / {{ round($total/$count, 1) }}</td>
        <td colspan="2"></td>
    </tr>
    @endif
    </tbody>
</table>

<div class="footer">Generated by Y GRO Student Management System · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
