<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Year Report {{ $academicYear->year }} – {{ $student->name }}</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #222; }
    .header { text-align: center; border-bottom: 2px solid #1e3a5f; padding-bottom: 12px; margin-bottom: 16px; }
    .header h2 { margin: 0; color: #1e3a5f; font-size: 16px; }
    .header h3 { margin: 4px 0 0; font-size: 13px; color: #555; }
    table.marks { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    table.marks th { background: #1e3a5f; color: #fff; padding: 5px 8px; font-size: 10px; text-align: left; }
    table.marks td { padding: 4px 8px; border-bottom: 1px solid #eee; }
    .term-heading { background: #e0e7ff; font-weight: bold; padding: 6px 8px; margin: 10px 0 4px; font-size: 11px; }
    .grade-A { color: #059669; font-weight: bold; }
    .grade-W { color: #dc2626; font-weight: bold; }
    .footer { margin-top: 30px; font-size: 9px; color: #888; text-align: center; }
</style>
</head>
<body>
<div class="header">
    <h2>Y GRO Student Management System</h2>
    <h3>Annual Academic Report – {{ $academicYear->year }} | {{ $student->name }}</h3>
</div>

@forelse($marks as $term => $termMarks)
<div class="term-heading">Term {{ $term }}</div>
<table class="marks">
    <thead><tr><th>#</th><th>Subject</th><th>Marks</th><th>Grade</th></tr></thead>
    <tbody>
    @foreach($termMarks as $i => $m)
        <tr>
            <td>{{ $i+1 }}</td>
            <td>{{ $m->subject->name }}</td>
            <td>{{ $m->marks }}</td>
            <td class="grade-{{ $m->grade_letter }}">{{ $m->grade_letter }}</td>
        </tr>
    @endforeach
    </tbody>
</table>
@empty
<p style="text-align:center;color:#888;">No marks recorded for {{ $academicYear->year }}.</p>
@endforelse

<div class="footer">Generated by Y GRO Student Management System · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
